# frozen_string_literal: true

require('starkcore')
require_relative('pix_internal_transaction_report')
require_relative('../utils/rest')


module StarkInfra
  class PixInternalTransactionReport
    # # PixInternalTransactionReport::Log object
    #
    # Every time a PixInternalTransactionReport entity is updated, a corresponding
    # PixInternalTransactionReport::Log is generated for the entity. This log is
    # never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - report [PixInternalTransactionReport object]: PixInternalTransactionReport entity to which the log refers to.
    # - type [string]: type of the PixInternalTransactionReport event which triggered the log creation. ex: 'created', 'failed', 'sent' or 'success'
    # - errors [list of strings]: list of errors linked to this PixInternalTransactionReport event.
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :errors, :report
      def initialize(id:, created:, type:, errors:, report:)
        super(id)
        @created = StarkCore::Utils::Checks.check_datetime(created)
        @type = type
        @errors = errors
        @report = report
      end

      # # Retrieve a specific PixInternalTransactionReport::Log
      #
      # Receive a single PixInternalTransactionReport::Log object previously created by the Stark Infra API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - PixInternalTransactionReport::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve PixInternalTransactionReport::Logs
      #
      # Receive a generator of PixInternalTransactionReport::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. ex: 'success' or 'failed'
      # - report_ids [list of strings, default nil]: list of PixInternalTransactionReport ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: Log ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - generator of PixInternalTransactionReport::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, types: nil, report_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          report_ids: report_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged PixInternalTransactionReport::Logs
      #
      # Receive a list of up to 100 PixInternalTransactionReport::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your logs.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. ex: 'success' or 'failed'
      # - report_ids [list of strings, default nil]: list of PixInternalTransactionReport ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: Log ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - list of PixInternalTransactionReport::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, ids: nil, limit: nil, after: nil, before: nil, types: nil, report_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          report_ids: report_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        report_maker = StarkInfra::PixInternalTransactionReport.resource[:resource_maker]
        {
          resource_name: 'PixInternalTransactionReportLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              report: StarkCore::Utils::API.from_api_json(report_maker, json['report']),
              type: json['type'],
              errors: json['errors'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
