# frozen_string_literal: true

require('starkcore')
require_relative('pix_pull_subscription')
require_relative('../utils/rest')

module StarkInfra
  class PixPullSubscription
    # # PixPullSubscription::Log object
    #
    # Every time a PixPullSubscription entity is modified, a corresponding PixPullSubscription::Log
    # is generated for the entity. This log is never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - subscription [PixPullSubscription]: PixPullSubscription entity to which the log refers to.
    # - type [string]: type of the PixPullSubscription event which triggered the log creation. Options: 'created', 'delivering', 'delivered', 'failed', 'approved', 'denied', 'confirmed', 'expired', 'canceling', 'canceled'
    # - errors [list of strings]: list of errors linked to this PixPullSubscription event.
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :subscription, :type, :errors, :created
      def initialize(id:, subscription:, type:, errors:, created:)
        super(id)
        @subscription = subscription
        @type = type
        @errors = errors
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific PixPullSubscription::Log
      #
      # Receive a single PixPullSubscription::Log object previously created by the Stark Infra API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - PixPullSubscription::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve PixPullSubscription::Logs
      #
      # Receive a generator of PixPullSubscription::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - ids [list of strings, default nil]: Log ids to filter PixPullSubscription Logs. ex: ['5656565656565656']
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. Options: 'created', 'delivering', 'delivered', 'failed', 'approved', 'denied', 'confirmed', 'expired', 'canceling', 'canceled'
      # - subscription_ids [list of strings, default nil]: list of PixPullSubscription ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - generator of PixPullSubscription::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, types: nil, subscription_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          subscription_ids: subscription_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged PixPullSubscription::Logs
      #
      # Receive a list of up to 100 PixPullSubscription::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your subscriptions.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - ids [list of strings, default nil]: Log ids to filter PixPullSubscription Logs. ex: ['5656565656565656']
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. Options: 'created', 'delivering', 'delivered', 'failed', 'approved', 'denied', 'confirmed', 'expired', 'canceling', 'canceled'
      # - subscription_ids [list of strings, default nil]: list of PixPullSubscription ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - list of PixPullSubscription::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, ids: nil, limit: nil, after: nil, before: nil, types: nil, subscription_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          subscription_ids: subscription_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        subscription_maker = StarkInfra::PixPullSubscription.resource[:resource_maker]
        {
          resource_name: 'PixPullSubscriptionLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              subscription: StarkCore::Utils::API.from_api_json(subscription_maker, json['subscription']),
              type: json['type'],
              errors: json['errors'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
