# frozen_string_literal: true

require('starkcore')
require_relative('../utils/rest')
require_relative('ledger')

module StarkInfra
  class Ledger
    # # Ledger::Log object
    #
    # Every time a Ledger entity is updated, a corresponding Ledger::Log
    # is generated for the entity. This log is never generated by the
    # user, but it can be retrieved to check additional information
    # on the Ledger.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    # - type [string]: type of the Ledger event which triggered the log creation. ex: 'created', 'updated'
    # - ledger [Ledger]: Ledger entity to which the log refers to.
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :ledger
      def initialize(id:, created:, type:, ledger:)
        super(id)
        @type = type
        @ledger = ledger
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific Ledger::Log
      #
      # Receive a single Ledger::Log object previously created by the Stark Infra API by its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - Ledger::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve Ledger::Logs
      #
      # Receive a generator of Ledger::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - ids [list of strings, default nil]: list of LedgerLog ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - ledger_id [string, default nil]: filter logs by Ledger id. ex: '5656565656565656'
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - generator of Ledger::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, ledger_id: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          ledger_id: ledger_id,
          user: user,
          **resource
        )
      end

      # # Retrieve paged Ledger::Logs
      #
      # Receive a list of up to 100 Ledger::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - ids [list of strings, default nil]: list of LedgerLog ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - ledger_id [string, default nil]: filter logs by Ledger id. ex: '5656565656565656'
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - list of Ledger::Log objects with updated attributes
      # - cursor to retrieve the next page of Ledger::Log objects
      def self.page(ids: nil, limit: nil, after: nil, before: nil, ledger_id: nil, cursor: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          ledger_id: ledger_id,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkInfra::Ledger.resource[:resource_maker]
        {
          resource_name: 'LedgerLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              created: json['created'],
              type: json['type'],
              ledger: StarkCore::Utils::API.from_api_json(request_maker, json['ledger'])
            )
          }
        }
      end
    end
  end
end
