# frozen_string_literal: true

require('starkcore')
require_relative('../utils/rest')
require_relative('business_account_request')

module StarkInfra
  class BusinessAccountRequest
    # # BusinessAccountRequest::Log object
    #
    # Every time a BusinessAccountRequest entity is modified, a corresponding BusinessAccountRequest::Log
    # is generated for the entity. This log is never generated by the user, but it can be retrieved to
    # check additional information on the BusinessAccountRequest.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - request [BusinessAccountRequest]: BusinessAccountRequest entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this BusinessAccountRequest event
    # - type [string]: type of the BusinessAccountRequest event which triggered the log creation. ex: 'created', 'processing', 'approved', 'denied', 'failed'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :request, :errors, :type, :created
      def initialize(id: nil, request: nil, errors: nil, type: nil, created: nil)
        super(id)
        @request = request
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific BusinessAccountRequest::Log
      #
      # Receive a single BusinessAccountRequest::Log object previously created by the Stark Infra API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - BusinessAccountRequest::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve BusinessAccountRequest::Logs
      #
      # Receive a generator of BusinessAccountRequest::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'processing', 'approved', 'denied', 'failed']
      # - account_request_ids [list of strings, default nil]: list of BusinessAccountRequest ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkinfra.user was set before function call
      #
      # ## Return:
      # - generator of BusinessAccountRequest::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, account_request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          account_request_ids: account_request_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged BusinessAccountRequest::Logs
      #
      # Receive a list of up to 100 BusinessAccountRequest::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 50
      # - after [Date or string, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'processing', 'approved', 'denied', 'failed']
      # - account_request_ids [list of strings, default nil]: list of BusinessAccountRequest ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkinfra.user was set before function call
      #
      # ## Return:
      # - list of BusinessAccountRequest::Log objects with updated attributes
      # - cursor to retrieve the next page of BusinessAccountRequest::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, account_request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          account_request_ids: account_request_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkInfra::BusinessAccountRequest.resource[:resource_maker]
        {
          resource_name: 'BusinessAccountRequestLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              request: StarkCore::Utils::API.from_api_json(request_maker, json['request']),
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
