# frozen_string_literal: true

require('starkcore')
require_relative('../utils/rest')
require_relative('credit_holmes')

module StarkInfra
  class CreditHolmes
    # # CreditHolmes::Log object
    #
    # Every time a CreditHolmes entity is updated, a corresponding CreditHolmes::Log
    # is generated for the entity. This log is never generated by the
    # user, but it can be retrieved to check additional information
    # on the CreditHolmes.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - holmes [CreditHolmes]: CreditHolmes entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this CreditHolmes event.
    # - type [string]: type of the CreditHolmes event which triggered the log creation. ex: 'created', 'failed', 'success'
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :created, :type, :errors, :holmes
      def initialize(id:, created:, type:, errors:, holmes:)
        super(id)
        @holmes = holmes
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific CreditHolmes::Log
      #
      # Receive a single CreditHolmes::Log object previously created by the Stark Infra API by its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - CreditHolmes::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve CreditHolmes::Logs
      #
      # Receive a generator of CreditHolmes::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'failed', 'success']
      # - holmes_ids [list of strings, default nil]: list of CreditHolmes ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - generator of CreditHolmes::Log objects with updated attributes
      def self.query(limit: nil, after: nil, before: nil, types: nil, holmes_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          limit: limit,
          after: after,
          before: before,
          types: types,
          holmes_ids: holmes_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged CreditHolmes::Logs
      #
      # Receive a list of up to 100 CreditHolmes::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: ['created', 'failed', 'success']
      # - holmes_ids [list of strings, default nil]: list of CreditHolmes ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - list of CreditHolmes::Log objects with updated attributes
      # - cursor to retrieve the next page of CreditHolmes::Log objects
      def self.page(cursor: nil, limit: nil, after: nil, before: nil, types: nil, holmes_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          limit: limit,
          after: after,
          before: before,
          types: types,
          holmes_ids: holmes_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        holmes_maker = StarkInfra::CreditHolmes.resource[:resource_maker]
        {
          resource_name: 'CreditHolmesLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              holmes: StarkCore::Utils::API.from_api_json(holmes_maker, json['holmes']),
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
