# frozen_string_literal: true

require('starkcore')
require_relative('../utils/rest')
require_relative('business_identity')

module StarkInfra
  class BusinessIdentity
    # # BusinessIdentity::Log object
    #
    # Every time a BusinessIdentity entity is updated, a corresponding BusinessIdentity::Log is generated for the entity.
    # This Log is never generated by the user, but it can be retrieved to check additional information on the BusinessIdentity.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - identity [BusinessIdentity]: BusinessIdentity entity to which the log refers to.
    # - errors [list of strings]: list of errors linked to this BusinessIdentity event
    # - type [string]: type of the BusinessIdentity event which triggered the log creation. ex: "created", "updated", "canceled", "processing", "success", "failed"
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :identity, :errors, :type, :created
      def initialize(id: nil, identity: nil, errors: nil, type: nil, created: nil)
        super(id)
        @identity = identity
        @errors = errors
        @type = type
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific BusinessIdentity::Log
      #
      # Receive a single BusinessIdentity::Log object previously created by the Stark Infra API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - BusinessIdentity::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve BusinessIdentity::Logs
      #
      # Receive a generator of BusinessIdentity::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: "created", "updated", "canceled", "processing", "success", "failed"
      # - identity_ids [list of strings, default nil]: list of identity ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: Log ids to filter BusinessIdentity Logs. ex: ['5656565656565656']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkinfra.user was set before function call
      #
      # ## Return:
      # - generator of BusinessIdentity::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, types: nil, identity_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          identity_ids: identity_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged BusinessIdentity::Logs
      #
      # Receive a list of up to 100 BusinessIdentity::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your identities.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil] date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil] date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter for log event types. ex: "created", "updated", "canceled", "processing", "success", "failed"
      # - identity_ids [list of strings, default nil]: list of identity ids to filter logs. ex: ['5656565656565656', '4545454545454545']
      # - ids [list of strings, default nil]: Log ids to filter BusinessIdentity Logs. ex: ['5656565656565656']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkinfra.user was set before function call
      #
      # ## Return:
      # - list of BusinessIdentity::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, ids: nil, limit: nil, after: nil, before: nil, types: nil, identity_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          identity_ids: identity_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkInfra::BusinessIdentity.resource[:resource_maker]
        {
          resource_name: 'BusinessIdentityLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              identity: StarkCore::Utils::API.from_api_json(request_maker, json['identity']),
              errors: json['errors'],
              type: json['type'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
