# frozen_string_literal: true

require('starkcore')
require_relative('pix_pull_request')
require_relative('../utils/rest')

module StarkInfra
  class PixPullRequest
    # # PixPullRequest::Log object
    #
    # Every time a PixPullRequest entity is modified, a corresponding PixPullRequest::Log
    # is generated for the entity. This log is never generated by the user.
    #
    # ## Attributes (return-only):
    # - id [string]: unique id returned when the log is created. ex: '5656565656565656'
    # - request [PixPullRequest]: PixPullRequest entity to which the log refers to.
    # - type [string]: type of the PixPullRequest event which triggered the log creation. Options: 'created', 'sent', 'scheduled', 'denied', 'success', 'canceling', 'canceled', 'expired'
    # - errors [list of strings]: list of errors linked to this PixPullRequest event. Empty list when the type is non-failing.
    # - created [DateTime]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
    class Log < StarkCore::Utils::Resource
      attr_reader :id, :request, :type, :errors, :created
      def initialize(id:, request:, type:, errors:, created:)
        super(id)
        @request = request
        @type = type
        @errors = errors.nil? ? [] : errors
        @created = StarkCore::Utils::Checks.check_datetime(created)
      end

      # # Retrieve a specific PixPullRequest::Log
      #
      # Receive a single PixPullRequest::Log object previously created by the Stark Infra API by passing its id
      #
      # ## Parameters (required):
      # - id [string]: object unique id. ex: '5656565656565656'
      #
      # ## Parameters (optional):
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - PixPullRequest::Log object with updated attributes
      def self.get(id, user: nil)
        StarkInfra::Utils::Rest.get_id(id: id, user: user, **resource)
      end

      # # Retrieve PixPullRequest::Logs
      #
      # Receive a generator of PixPullRequest::Log objects previously created in the Stark Infra API
      #
      # ## Parameters (optional):
      # - ids [list of strings, default nil]: Log ids to filter PixPullRequest Logs. ex: ['5656565656565656']
      # - limit [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. Options: 'created', 'sent', 'scheduled', 'denied', 'success', 'canceling', 'canceled', 'expired'
      # - request_ids [list of strings, default nil]: list of PixPullRequest ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - generator of PixPullRequest::Log objects with updated attributes
      def self.query(ids: nil, limit: nil, after: nil, before: nil, types: nil, request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_stream(
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          request_ids: request_ids,
          user: user,
          **resource
        )
      end

      # # Retrieve paged PixPullRequest::Logs
      #
      # Receive a list of up to 100 PixPullRequest::Log objects previously created in the Stark Infra API and the cursor to the next page.
      # Use this function instead of query if you want to manually page your requests.
      #
      # ## Parameters (optional):
      # - cursor [string, default nil]: cursor returned on the previous page function call
      # - ids [list of strings, default nil]: Log ids to filter PixPullRequest Logs. ex: ['5656565656565656']
      # - limit [integer, default 100]: maximum number of objects to be retrieved. Max = 100. ex: 35
      # - after [Date or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
      # - before [Date or string, default nil]: date filter for objects created only before specified date. ex: Date.new(2020, 3, 10)
      # - types [list of strings, default nil]: filter retrieved objects by types. Options: 'created', 'sent', 'scheduled', 'denied', 'success', 'canceling', 'canceled', 'expired'
      # - request_ids [list of strings, default nil]: list of PixPullRequest ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
      # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
      #
      # ## Return:
      # - list of PixPullRequest::Log objects with updated attributes
      # - cursor to retrieve the next page of Log objects
      def self.page(cursor: nil, ids: nil, limit: nil, after: nil, before: nil, types: nil, request_ids: nil, user: nil)
        after = StarkCore::Utils::Checks.check_date(after)
        before = StarkCore::Utils::Checks.check_date(before)
        StarkInfra::Utils::Rest.get_page(
          cursor: cursor,
          ids: ids,
          limit: limit,
          after: after,
          before: before,
          types: types,
          request_ids: request_ids,
          user: user,
          **resource
        )
      end

      def self.resource
        request_maker = StarkInfra::PixPullRequest.resource[:resource_maker]
        {
          resource_name: 'PixPullRequestLog',
          resource_maker: proc { |json|
            Log.new(
              id: json['id'],
              request: StarkCore::Utils::API.from_api_json(request_maker, json['request']),
              type: json['type'],
              errors: json['errors'],
              created: json['created']
            )
          }
        }
      end
    end
  end
end
